// apps/angular-storefront/src/app/features/checkout/components/order-summary/order-summary.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { OkklyIcon, OkklyTypography } from '@okkly/angular';
import { iconImage } from '@okkly/icons';
import type { HttpTypes } from '@medusajs/types';
import { formatPrice } from '../../../products/product-price';

/**
 * The cart's items and totals beside the checkout steps, ported from the
 * Vue storefront's `OrderSummary`. The step's action button is projected in
 * at the bottom.
 */
@Component({
  selector: 'app-order-summary',
  imports: [OkklyIcon, OkklyTypography],
  template: `
    <ul class="order-summary__items">
      @for (item of items(); track item.id) {
        <li class="order-summary__item">
          <div class="order-summary__item-media">
            @if (item.thumbnail; as thumbnail) {
              <img [src]="thumbnail" [alt]="item.title" class="order-summary__item-image" />
            } @else {
              <div class="order-summary__item-fallback" aria-hidden="true">
                <okkly-icon [icon]="iconImage" fontSize="small" />
              </div>
            }
            <span class="order-summary__item-qty">{{ item.quantity }}</span>
          </div>
          <div class="order-summary__item-body">
            <span okklyTypography variant="label-sm" class="order-summary__item-title">{{ item.title }}</span>
            @if (variantLabel(item); as label) {
              <span okklyTypography variant="caption" color="muted">{{ label }}</span>
            }
          </div>
          <span okklyTypography variant="label-sm" class="order-summary__item-price">
            {{ price(item.unit_price * item.quantity) }}
          </span>
        </li>
      }
    </ul>

    <hr class="order-summary__divider" />

    <div class="order-summary__totals">
      <div class="order-summary__row">
        <span okklyTypography variant="body-sm" color="secondary">Subtotal</span>
        <span okklyTypography variant="body-sm">{{ price(subtotal()) }}</span>
      </div>
      <div class="order-summary__row">
        <span okklyTypography variant="body-sm" color="secondary">Shipping</span>
        <span okklyTypography variant="body-sm">{{ formattedShipping() }}</span>
      </div>
      <hr class="order-summary__divider" />
      <div class="order-summary__row">
        <span okklyTypography variant="label-md">Total</span>
        <span okklyTypography variant="h4">{{ price(total()) }}</span>
      </div>
    </div>

    <div class="order-summary__action">
      <ng-content />
    </div>
  `,
  styleUrl: './order-summary.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OrderSummary {
  readonly items = input.required<HttpTypes.StoreCartLineItem[]>();
  readonly currencyCode = input.required<string>();
  /** Items only — Medusa's own `subtotal` already includes shipping, which has its own row here. */
  readonly subtotal = input.required<number>();
  /** `null` while no shipping method is chosen yet — shown as "Calculated next". */
  readonly shipping = input.required<number | null>();
  readonly total = input.required<number>();

  protected readonly iconImage = iconImage;

  protected readonly formattedShipping = computed(() => {
    const shipping = this.shipping();
    return shipping === null ? 'Calculated next' : this.price(shipping);
  });

  protected variantLabel(item: HttpTypes.StoreCartLineItem): string | null {
    return item.variant_title?.replace(/\s*\/\s*/g, ' · ') ?? null;
  }

  protected price(amount: number): string {
    return formatPrice({ amount, currencyCode: this.currencyCode(), originalAmount: null });
  }
}

// apps/vue-storefront/app/features/checkout/components/OrderSummary.vue
<script setup lang="ts">
import { computed } from "vue"

import { Icon, Typography } from "@okkly/vue"

import { formatPrice } from "~/features/products"
import type { CartLineItem } from "~/shared/types/medusa"

const props = defineProps<{
  items: CartLineItem[]
  currencyCode: string
  subtotal: number
  /** `null` while no shipping method is chosen yet - shown as "Calculated next". */
  shipping: number | null
  total: number
}>()

const variantLabel = (item: CartLineItem) =>
  item.variant_title?.replace(/\s*\/\s*/g, " · ") ?? null

const price = (amount: number) =>
  formatPrice({
    amount,
    currencyCode: props.currencyCode,
    originalAmount: null,
  })

const formattedSubtotal = computed(() => price(props.subtotal))
const formattedShipping = computed(() =>
  props.shipping === null ? "Calculated next" : price(props.shipping)
)
const formattedTotal = computed(() => price(props.total))
</script>

<template>
  <aside class="order-summary">
    <ul class="order-summary__items">
      <li v-for="item in items" :key="item.id" class="order-summary__item">
        <div class="order-summary__item-media">
          <img
            v-if="item.thumbnail"
            :src="item.thumbnail"
            :alt="item.title"
            class="order-summary__item-image"
          />
          <div v-else class="order-summary__item-fallback" aria-hidden="true">
            <Icon name="iconImage" font-size="small" />
          </div>
          <span class="order-summary__item-qty">{{ item.quantity }}</span>
        </div>
        <div class="order-summary__item-body">
          <Typography variant="label-sm" class="order-summary__item-title">
            {{ item.title }}
          </Typography>
          <Typography v-if="variantLabel(item)" variant="caption" color="muted">
            {{ variantLabel(item) }}
          </Typography>
        </div>
        <Typography
          variant="label-sm"
          as="span"
          class="order-summary__item-price"
        >
          {{ price(item.unit_price * item.quantity) }}
        </Typography>
      </li>
    </ul>

    <hr class="order-summary__divider" />

    <div class="order-summary__totals">
      <div class="order-summary__row">
        <Typography variant="body-sm" color="secondary">Subtotal</Typography>
        <Typography variant="body-sm">{{ formattedSubtotal }}</Typography>
      </div>
      <div class="order-summary__row">
        <Typography variant="body-sm" color="secondary">Shipping</Typography>
        <Typography variant="body-sm">{{ formattedShipping }}</Typography>
      </div>
      <hr class="order-summary__divider" />
      <div class="order-summary__row">
        <Typography variant="label-md">Total</Typography>
        <Typography variant="h4">{{ formattedTotal }}</Typography>
      </div>
    </div>

    <div class="order-summary__action">
      <slot name="action" />
    </div>
  </aside>
</template>

<style scoped>
.order-summary {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-4);
  width: 100%;
  padding: var(--okkly-space-5);
  border: 1px solid var(--okkly-border-subtle);
  border-radius: var(--okkly-radius-lg);
  background: var(--okkly-glass-fill);
}

.order-summary__items {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-4);
  margin: 0;
  padding: 0;
  list-style: none;
  max-height: 20rem;
  overflow-y: auto;
}

.order-summary__item {
  display: flex;
  align-items: center;
  gap: var(--okkly-space-3);
}

.order-summary__item-media {
  position: relative;
  flex-shrink: 0;
  width: 3rem;
  height: 3rem;
  overflow: hidden;
  border: 1px solid var(--okkly-border-subtle);
  border-radius: var(--okkly-radius-md);
  background: var(--okkly-bg-inset);
}

.order-summary__item-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.order-summary__item-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: var(--okkly-text-muted);
}

.order-summary__item-qty {
  position: absolute;
  top: -0.375rem;
  right: -0.375rem;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 1.125rem;
  height: 1.125rem;
  padding: 0 0.25rem;
  border-radius: var(--okkly-radius-full);
  background: var(--okkly-bg-surface-raised);
  border: 1px solid var(--okkly-border-default);
  font-size: 0.6875rem;
  font-weight: var(--okkly-font-weight-medium);
  color: var(--okkly-text-secondary);
}

.order-summary__item-body {
  display: flex;
  flex: 1 1 auto;
  flex-direction: column;
  gap: 0.125rem;
  min-width: 0;
}

.order-summary__item-title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.order-summary__item-price {
  flex-shrink: 0;
}

.order-summary__divider {
  width: 100%;
  height: 1px;
  margin: 0;
  border: none;
  background: var(--okkly-border-subtle);
}

.order-summary__totals {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-2);
}

.order-summary__row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.order-summary__action {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-2);
}
</style>
