// apps/angular-ngrx-storefront/src/app/features/checkout/components/steps/delivery-step.ts
import { ChangeDetectionStrategy, Component, computed, effect, forwardRef, inject, signal, untracked } from '@angular/core';
import { form, submit } from '@angular/forms/signals';
import { Actions } from '@ngrx/effects';
import { Store } from '@ngrx/store';
import { OkklyRadio, OkklyRadioGroup, OkklySkeleton, OkklyTypography } from '@okkly/angular';
import { PricePipe } from '../../../../shared/pipes/price-pipe';
import { CART_MUTATION_RESULTS, CartActions, CartApiActions } from '../../../../state/cart/cart.actions';
import { dispatchAndWait } from '../../../../state/dispatch-and-wait';
import { ShippingOptionsActions } from '../../../../state/shipping-options/shipping-options.actions';
import { shippingOptionsFeature } from '../../../../state/shipping-options/shipping-options.reducer';
import { deliverySchema, visibleError } from '../../checkout-forms';
import { CHECKOUT_STEP, CheckoutPage, type CheckoutStepHandle } from '../../checkout-page';

/** Ported from the Vue storefront's `DeliveryStep`: picks the cart's shipping option. */
@Component({
  selector: 'app-delivery-step',
  imports: [OkklyRadio, OkklyRadioGroup, OkklySkeleton, OkklyTypography, PricePipe],
  providers: [{ provide: CHECKOUT_STEP, useExisting: forwardRef(() => DeliveryStep) }],
  template: `
    <h1 okklyTypography variant="h2">Delivery</h1>

    <form class="step-form" novalidate (submit)="$event.preventDefault(); submit()">
      <div class="step-form__intro">
        <span okklyTypography variant="label-md">Shipping method</span>
        <span okklyTypography variant="body-sm" color="muted">How would you like your order delivered</span>
      </div>

      @if (optionsPending()) {
        <div class="step-options" aria-busy="true">
          <okkly-skeleton variant="rectangular" height="4.5rem" />
          <okkly-skeleton variant="rectangular" height="4.5rem" />
        </div>
      } @else {
        <!--
          Not [formField]: the group's value is \`string | undefined\`, which
          doesn't fit this \`string\` field as a FormValueControl.
        -->
        <okkly-radio-group
          class="step-options"
          label="Shipping method"
          [value]="form.shippingOptionId().value()"
          (valueChange)="form.shippingOptionId().value.set($event ?? '')"
        >
          @for (option of shippingOptions(); track option.id) {
            <label class="step-option" [class.step-option--selected]="option.id === form.shippingOptionId().value()">
              <okkly-radio [value]="option.id" [attr.aria-label]="option.name" />
              <span okklyTypography variant="label-md" class="step-option__name">{{ option.name }}</span>
              <span okklyTypography variant="label-md">{{ option.calculated_price?.calculated_amount ?? 0 | price: currencyCode() }}</span>
            </label>
          }
        </okkly-radio-group>
      }

      @if (error(form.shippingOptionId) ?? serverError() ?? optionsError(); as message) {
        <p okklyTypography variant="body-sm" color="danger">{{ message }}</p>
      }
    </form>
  `,
  styleUrl: './step.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DeliveryStep implements CheckoutStepHandle {
  private readonly page = inject(CheckoutPage);
  private readonly store = inject(Store);
  private readonly actions$ = inject(Actions);

  protected readonly shippingOptions = this.store.selectSignal(shippingOptionsFeature.selectShippingOptions);
  protected readonly optionsError = this.store.selectSignal(shippingOptionsFeature.selectError);
  private readonly optionsCartId = this.store.selectSignal(shippingOptionsFeature.selectCartId);
  private readonly optionsLoading = this.store.selectSignal(shippingOptionsFeature.selectLoading);

  protected readonly error = visibleError;
  protected readonly currencyCode = computed(() => this.page.cart()?.currency_code ?? 'usd');

  private readonly model = signal({
    shippingOptionId: this.page.cart()?.shipping_methods?.[0]?.shipping_option_id ?? '',
  });
  protected readonly form = form(this.model, deliverySchema);

  readonly isPending = computed(() => this.form().submitting());

  protected readonly serverError = computed(
    () => this.form().errors().find((error) => error.kind === 'server')?.message ?? null,
  );

  /** Options loaded for a different cart (or not at all) aren't this cart's yet. */
  protected readonly optionsPending = computed(
    () =>
      this.optionsError() === null &&
      (this.optionsCartId() !== this.page.cart()?.id || this.optionsLoading()),
  );

  constructor() {
    const cartId = this.page.cart()?.id;
    // Prices depend on the cart's contents and address, which may have
    // changed since the options were last loaded.
    if (cartId) this.store.dispatch(ShippingOptionsActions.refresh({ cartId }));

    // Nothing is pre-selected until the options arrive — default to the
    // first one once they do, rather than leaving an obvious choice empty.
    effect(() => {
      const first = this.optionsPending() ? undefined : this.shippingOptions()[0];
      const field = untracked(() => this.form.shippingOptionId());

      if (first && !untracked(field.value)) {
        field.value.set(first.id);
      }
    });
  }

  async submit(): Promise<void> {
    await submit(this.form, async () => {
      const result = await dispatchAndWait(
        this.store,
        this.actions$,
        CartActions.addShippingMethod({ body: { option_id: this.model().shippingOptionId } }),
        CART_MUTATION_RESULTS,
      );
      if (result.type !== CartApiActions.mutationSucceeded.type) return { kind: 'server', message: result.error };

      await this.page.goToStep('payment');
      return undefined;
    });
  }
}

// apps/vue-storefront/app/features/checkout/components/steps/DeliveryStep.vue
<script setup lang="ts">
import { computed, watch } from "vue"
import { toTypedSchema } from "@vee-validate/zod"
import { useForm } from "vee-validate"

import { Radio, RadioGroup, Skeleton, Typography } from "@okkly/vue"

import { formatPrice } from "~/features/products"

import { deliveryStepSchema } from "../../schemas"
import { useCheckoutPage } from "../../useCheckoutPage"

const { cart, goToStep, cartRefetch } = useCheckoutPage()

const { shippingOptions, shippingOptionsIsPending } = useShippingOptions(
  () => ({
    query: { cart_id: cart.value?.id ?? "" },
    enabled: cart.value?.id !== undefined,
  })
)

const options = computed(() => shippingOptions.value?.shipping_options ?? [])

const { handleSubmit, defineField, setFieldValue } = useForm({
  validationSchema: toTypedSchema(deliveryStepSchema),
  initialValues: {
    shippingOptionId:
      cart.value?.shipping_methods?.[0]?.shipping_option_id ?? "",
  },
})

const [shippingOptionId] = defineField("shippingOptionId")

// Nothing is pre-selected until the options arrive - default to the first
// one once they do, rather than leaving the visitor to fill in an obvious
// choice by hand.
watch(
  options,
  (value) => {
    const first = value[0]

    if (!shippingOptionId.value && first) {
      setFieldValue("shippingOptionId", first.id)
    }
  },
  { immediate: true }
)

const {
  addShippingMethodMutateAsync,
  addShippingMethodIsPending,
  addShippingMethodError,
} = useAddShippingMethod()

const onSubmit = handleSubmit(async (values) => {
  if (!cart.value) return

  await addShippingMethodMutateAsync({
    cartId: cart.value.id,
    body: { option_id: values.shippingOptionId },
  })

  await cartRefetch()
  goToStep("payment")
})

defineExpose({
  submit: onSubmit,
  isPending: computed(() => addShippingMethodIsPending.value),
})
</script>

<template>
  <div class="delivery-step">
    <Typography variant="h2" as="h1">Delivery</Typography>

    <form class="delivery-step__form" @submit="onSubmit">
      <div class="delivery-step__intro">
        <Typography variant="label-md">Shipping method</Typography>
        <Typography variant="body-sm" color="muted">
          How would you like your order delivered
        </Typography>
      </div>

      <div v-if="shippingOptionsIsPending" class="delivery-step__options">
        <Skeleton variant="rectangular" height="4.5rem" />
        <Skeleton variant="rectangular" height="4.5rem" />
      </div>

      <RadioGroup
        v-else
        v-model="shippingOptionId"
        class="delivery-step__options"
      >
        <label
          v-for="option in options"
          :key="option.id"
          class="delivery-option"
          :class="{
            'delivery-option--selected': option.id === shippingOptionId,
          }"
        >
          <Radio :value="option.id" />
          <Typography variant="label-md" class="delivery-option__name">
            {{ option.name }}
          </Typography>
          <Typography variant="label-md" as="span">
            {{
              formatPrice({
                amount: option.calculated_price?.calculated_amount ?? 0,
                currencyCode: cart?.currency_code ?? "usd",
                originalAmount: null,
              })
            }}
          </Typography>
        </label>
      </RadioGroup>

      <Typography
        v-if="addShippingMethodError"
        variant="body-sm"
        color="danger"
      >
        {{ addShippingMethodError.message }}
      </Typography>
    </form>
  </div>
</template>

<style scoped>
.delivery-step {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-6);
}

.delivery-step__form {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-4);
}

.delivery-step__intro {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-1);
}

.delivery-step__options {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-3);
}

.delivery-option {
  display: flex;
  align-items: center;
  gap: var(--okkly-space-3);
  padding: var(--okkly-space-4);
  border: 1px solid var(--okkly-border-default);
  border-radius: var(--okkly-radius-lg);
  cursor: pointer;
  transition: border-color 160ms ease;
}

.delivery-option--selected {
  border-color: var(--okkly-accent-primary);
}

.delivery-option__name {
  flex: 1 1 auto;
}
</style>
