// apps/vue-storefront/app/features/checkout/components/steps/PaymentStep.vue
<script setup lang="ts">
import { computed } from "vue"

import { Icon, Radio, Typography } from "@okkly/vue"

import { MANUAL_PAYMENT_PROVIDER_ID } from "../../constants"
import { useCheckoutPage } from "../../useCheckoutPage"

const PROVIDER_LABELS: Record<string, string> = {
  [MANUAL_PAYMENT_PROVIDER_ID]: "Manual Payment",
}

const { cart, goToStep, cartRefetch } = useCheckoutPage()

const { paymentProviders } = usePaymentProviders({
  query: { region_id: cart.value?.region_id ?? "" },
})

const providers = computed(
  () => paymentProviders.value?.payment_providers ?? []
)

const {
  createPaymentSessionMutateAsync,
  createPaymentSessionIsPending,
  createPaymentSessionError,
} = useCreatePaymentSession()

const onSubmit = async (event?: Event) => {
  event?.preventDefault()
  if (!cart.value) return

  await createPaymentSessionMutateAsync({
    cart: cart.value,
    body: { provider_id: MANUAL_PAYMENT_PROVIDER_ID },
  })

  await cartRefetch()
  goToStep("review")
}

defineExpose({
  submit: onSubmit,
  isPending: computed(() => createPaymentSessionIsPending.value),
})
</script>

<template>
  <div class="payment-step">
    <Typography variant="h2" as="h1">Payment</Typography>

    <form class="payment-step__form" @submit="onSubmit">
      <label
        v-for="provider in providers"
        :key="provider.id"
        class="payment-option payment-option--selected"
      >
        <Radio :checked="true" :value="provider.id" />
        <Typography variant="label-md">
          {{ PROVIDER_LABELS[provider.id] ?? provider.id }}
        </Typography>
        <span class="payment-option__notice"
          >Attention: For testing purposes only.</span
        >
        <Icon
          name="iconCreditCard"
          font-size="small"
          class="payment-option__icon"
        />
      </label>

      <Typography
        v-if="createPaymentSessionError"
        variant="body-sm"
        color="danger"
      >
        {{ createPaymentSessionError.message }}
      </Typography>
    </form>
  </div>
</template>

<style scoped>
.payment-step {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-6);
}

.payment-step__form {
  display: flex;
  flex-direction: column;
  gap: var(--okkly-space-3);
}

.payment-option {
  display: flex;
  align-items: center;
  gap: var(--okkly-space-3);
  padding: var(--okkly-space-4);
  border: 1px solid var(--okkly-accent-primary);
  border-radius: var(--okkly-radius-lg);
  cursor: default;
}

.payment-option__notice {
  padding: 0.25rem 0.625rem;
  border-radius: var(--okkly-radius-full);
  background: color-mix(
    in srgb,
    var(--okkly-feedback-warning) 16%,
    transparent
  );
  color: var(--okkly-feedback-warning);
  font-size: 0.8125rem;
  font-weight: var(--okkly-font-weight-medium);
}

.payment-option__icon {
  margin-left: auto;
  color: var(--okkly-text-muted);
}
</style>

// apps/angular-ngrx-storefront/src/app/features/checkout/components/steps/payment-step.ts
import { ChangeDetectionStrategy, Component, forwardRef, inject, signal } from '@angular/core';
import { Actions } from '@ngrx/effects';
import { Store } from '@ngrx/store';
import { OkklyIcon, OkklyRadio, OkklyTypography } from '@okkly/angular';
import { iconCreditCard } from '@okkly/icons';
import { CART_MUTATION_RESULTS, CartActions, CartApiActions } from '../../../../state/cart/cart.actions';
import { dispatchAndWait } from '../../../../state/dispatch-and-wait';
import { PaymentProvidersActions } from '../../../../state/payment-providers/payment-providers.actions';
import { paymentProvidersFeature } from '../../../../state/payment-providers/payment-providers.reducer';
import { MANUAL_PAYMENT_PROVIDER_ID } from '../../checkout.constants';
import { CHECKOUT_STEP, CheckoutPage, type CheckoutStepHandle } from '../../checkout-page';

const PROVIDER_LABELS: Record<string, string> = {
  [MANUAL_PAYMENT_PROVIDER_ID]: 'Manual Payment',
};

/**
 * Ported from the Vue storefront's `PaymentStep`. The store has a single,
 * manual provider, so there's nothing to choose and no form — submitting
 * just starts a payment session with it.
 */
@Component({
  selector: 'app-payment-step',
  imports: [OkklyIcon, OkklyRadio, OkklyTypography],
  providers: [{ provide: CHECKOUT_STEP, useExisting: forwardRef(() => PaymentStep) }],
  template: `
    <h1 okklyTypography variant="h2">Payment</h1>

    <form class="step-options" novalidate (submit)="$event.preventDefault(); submit()">
      @for (provider of paymentProviders(); track provider.id) {
        <label class="step-option step-option--selected payment-option">
          <okkly-radio [checked]="true" [value]="provider.id" [attr.aria-label]="label(provider.id)" />
          <span okklyTypography variant="label-md">{{ label(provider.id) }}</span>
          <span class="payment-option__notice">Attention: For testing purposes only.</span>
          <okkly-icon [icon]="iconCreditCard" fontSize="small" class="payment-option__icon" />
        </label>
      }

      @if (error() ?? providersError(); as message) {
        <p okklyTypography variant="body-sm" color="danger">{{ message }}</p>
      }
    </form>
  `,
  styleUrl: './step.scss',
  styles: `
    .payment-option {
      cursor: default;
    }

    .payment-option__notice {
      padding: 0.25rem 0.625rem;
      border-radius: var(--okkly-radius-full);
      background: color-mix(in srgb, var(--okkly-feedback-warning) 16%, transparent);
      color: var(--okkly-feedback-warning);
      font-size: 0.8125rem;
      font-weight: var(--okkly-font-weight-medium);
    }

    .payment-option__icon {
      margin-left: auto;
      color: var(--okkly-text-muted);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaymentStep implements CheckoutStepHandle {
  private readonly page = inject(CheckoutPage);
  private readonly store = inject(Store);
  private readonly actions$ = inject(Actions);

  protected readonly paymentProviders = this.store.selectSignal(paymentProvidersFeature.selectPaymentProviders);
  protected readonly providersError = this.store.selectSignal(paymentProvidersFeature.selectError);

  protected readonly iconCreditCard = iconCreditCard;

  private readonly pending = signal(false);
  readonly isPending = this.pending.asReadonly();
  protected readonly error = signal<string | null>(null);

  constructor() {
    const regionId = this.page.cart()?.region_id;
    if (regionId) this.store.dispatch(PaymentProvidersActions.load({ regionId }));
  }

  protected label(providerId: string): string {
    return PROVIDER_LABELS[providerId] ?? providerId;
  }

  async submit(): Promise<void> {
    if (this.pending()) return;

    this.pending.set(true);
    this.error.set(null);

    try {
      const result = await dispatchAndWait(
        this.store,
        this.actions$,
        CartActions.createPaymentSession({ body: { provider_id: MANUAL_PAYMENT_PROVIDER_ID } }),
        CART_MUTATION_RESULTS,
      );

      if (result.type === CartApiActions.mutationSucceeded.type) {
        await this.page.goToStep('review');
      } else {
        this.error.set(result.error);
      }
    } finally {
      this.pending.set(false);
    }
  }
}
